// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProdjaFutbolok.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Title { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public int? SalesCount { get; set; }

    public int ClothingTypeId { get; set; }

    public bool IsAvailable { get; set; }

    public virtual ClothingType ClothingType { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductInventory> ProductInventories { get; set; } = new List<ProductInventory>();
}