// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProdjaFutbolok.Models;

public partial class ProductInventory
{
    public int ProductId { get; set; }

    public int SizeId { get; set; }

    public int? StockQuantity { get; set; }

    public virtual Product Product { get; set; }

    public virtual Size Size { get; set; }
}